In [85]:
#задание 1
list_a=[(10, 20), (1), (30, 56, 25), (10, 20), (33, ), (40,), (200), (10, 42), (42), (1,2,3), (4,5,6), (10,11,12), (7,8,9)]
def summ(lst):
    llen = 0.
    s=0.
    for i in lst:
        s += i
    llen += 1
    return s
index=0
min_index=0
print (summ(list_a[0]))
for item in list_a:
    index+=1
    
    if (summ(int((item))<summ(list_a[0])):
        min_index=index
print (min_index)        
        
        
 

SyntaxError: invalid syntax (<ipython-input-85-ab9a6a107475>, line 16)

In [79]:
#задание 6
import numpy as np
#середнее арифметическое списка
def fl(lst):
    llen = 0.
    s=0.
    for i in lst:
        s += i
    llen += 1
    return s / len(lst)
matrix=np.array([(17,24,1,8,15),(23,5,7,14,16),(4,6,13,20,22),(10,12,19,21,3),(11,18,25,2,9)],dtype=float)

for column in matrix:
    
    for item in column:
        
        column-=fl(column)
    
print (matrix)    


[[  4.  11. -12.  -5.   2.]
 [ 10.  -8.  -6.   1.   3.]
 [ -9.  -7.   0.   7.   9.]
 [ -3.  -1.   6.   8. -10.]
 [ -2.   5.  12. -11.  -4.]]


In [95]:
#задание 9.1
import numpy as np
import pandas as pd

data = {'animal': ['cat', 'cat', 'snake', 'dog', 'dog', 'cat', 'snake', 'cat', 'dog', 'dog'],
        'age': [2.5, 3, 0.5, np.nan, 5, 2, 4.5, np.nan, 7, 3],
        'visits': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
        'priority': ['yes', 'yes', 'no', 'yes', 'no', 'no', 'no', 'yes', 'no', 'no']}

labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']
df=pd.DataFrame(data,index=labels)
print (df)
#задание 9.2
print (df.info())
print (df.shape)
#задание 9.3
print(df[:5])
#задание 9.4
print (df[['animal','age']])

   age animal priority  visits
a  2.5    cat      yes       1
b  3.0    cat      yes       3
c  0.5  snake       no       2
d  NaN    dog      yes       3
e  5.0    dog       no       2
f  2.0    cat       no       3
g  4.5  snake       no       1
h  NaN    cat      yes       1
i  7.0    dog       no       2
j  3.0    dog       no       1
<class 'pandas.core.frame.DataFrame'>
Index: 10 entries, a to j
Data columns (total 4 columns):
age         8 non-null float64
animal      10 non-null object
priority    10 non-null object
visits      10 non-null int64
dtypes: float64(1), int64(1), object(2)
memory usage: 400.0+ bytes
None
(10, 4)
   age animal priority  visits
a  2.5    cat      yes       1
b  3.0    cat      yes       3
c  0.5  snake       no       2
d  NaN    dog      yes       3
e  5.0    dog       no       2
  animal  age
a    cat  2.5
b    cat  3.0
c  snake  0.5
d    dog  NaN
e    dog  5.0
f    cat  2.0
g  snake  4.5
h    cat  NaN
i    dog  7.0
j    dog  3.0
